import type { Restaurant } from '../types';

/**
 * Curated Bangalore restaurant seed data for development and fallback.
 * These are used when Swiggy Dineout MCP is not available.
 */
export const BANGALORE_RESTAURANTS: Restaurant[] = [
  {
    id: "resto-001",
    name: "Toit Brewpub",
    cuisine: ["Craft Beer", "Continental", "Pizza"],
    area: "Indiranagar",
    address: "298, 100 Feet Road, Indiranagar, Bangalore",
    rating: 4.5,
    costForTwo: 1800,
    groupFriendly: true,
    maxGroupSize: 10,
    ambiance: ["Casual", "Lively", "Industrial"],
    highlights: ["Craft Beer", "Live Screens", "Group Tables"],
    lat: 12.9784,
    lng: 77.6408,
  },
  {
    id: "resto-002",
    name: "Meghana Foods",
    cuisine: ["Andhra", "Biryani", "South Indian"],
    area: "Koramangala",
    address: "124, 80 Feet Road, Koramangala 4th Block, Bangalore",
    rating: 4.4,
    costForTwo: 600,
    groupFriendly: true,
    maxGroupSize: 8,
    ambiance: ["Casual", "Family-Friendly"],
    highlights: ["Legendary Biryani", "Andhra Meals", "Quick Service"],
    lat: 12.9352,
    lng: 77.6245,
  },
  {
    id: "resto-003",
    name: "The Fatty Bao",
    cuisine: ["Asian", "Japanese", "Thai", "Dimsum"],
    area: "Indiranagar",
    address: "610, 12th Main, HAL 2nd Stage, Indiranagar, Bangalore",
    rating: 4.3,
    costForTwo: 2200,
    groupFriendly: true,
    maxGroupSize: 8,
    ambiance: ["Trendy", "Modern", "Vibrant"],
    highlights: ["Asian Fusion", "Craft Cocktails", "Bao Buns"],
    lat: 12.9716,
    lng: 77.6412,
  },
  {
    id: "resto-004",
    name: "Truffles",
    cuisine: ["American", "Burgers", "Continental"],
    area: "Koramangala",
    address: "28, 4th B Cross, Koramangala, Bangalore",
    rating: 4.5,
    costForTwo: 700,
    groupFriendly: true,
    maxGroupSize: 6,
    ambiance: ["Casual", "Cozy", "College-Vibe"],
    highlights: ["Best Burgers", "Generous Portions", "Affordable"],
    lat: 12.9346,
    lng: 77.6205,
  },
  {
    id: "resto-005",
    name: "Vidyarthi Bhavan",
    cuisine: ["South Indian", "Dosa", "Traditional"],
    area: "Basavanagudi",
    address: "32, Gandhi Bazaar Main Road, Basavanagudi, Bangalore",
    rating: 4.6,
    costForTwo: 300,
    groupFriendly: true,
    maxGroupSize: 6,
    ambiance: ["Heritage", "Traditional", "Iconic"],
    highlights: ["Legendary Masala Dosa", "Since 1943", "Must Visit"],
    lat: 12.9436,
    lng: 77.5712,
  },
  {
    id: "resto-006",
    name: "Brahmin's Coffee Bar",
    cuisine: ["South Indian", "Idli", "Traditional"],
    area: "Basavanagudi",
    address: "Ranga Rao Road, Shankarapuram, Basavanagudi, Bangalore",
    rating: 4.5,
    costForTwo: 150,
    groupFriendly: false,
    maxGroupSize: 4,
    ambiance: ["Heritage", "Standing-Only", "Iconic"],
    highlights: ["Iconic Idli-Vada", "Standing Breakfast", "Since 1965"],
    lat: 12.9489,
    lng: 77.5699,
  },
  {
    id: "resto-007",
    name: "Permit Room",
    cuisine: ["Modern Indian", "Bar Food", "Cocktails"],
    area: "Koramangala",
    address: "3rd Floor, KHB Colony, Koramangala 5th Block, Bangalore",
    rating: 4.2,
    costForTwo: 1600,
    groupFriendly: true,
    maxGroupSize: 10,
    ambiance: ["Retro", "Hip", "Bar-Style"],
    highlights: ["Innovative Cocktails", "Retro Decor", "Bar Snacks"],
    lat: 12.9341,
    lng: 77.6166,
  },
  {
    id: "resto-008",
    name: "Byg Brewski",
    cuisine: ["Multi-Cuisine", "Craft Beer", "BBQ"],
    area: "Sarjapur Road",
    address: "Sarjapur Road, Near Wipro Corporate Office, Bangalore",
    rating: 4.1,
    costForTwo: 2000,
    groupFriendly: true,
    maxGroupSize: 20,
    ambiance: ["Open-Air", "Party", "Massive"],
    highlights: ["Largest Brewpub", "Outdoor Seating", "Live Music"],
    lat: 12.9087,
    lng: 77.6791,
  },
  {
    id: "resto-009",
    name: "Smoke House Deli",
    cuisine: ["European", "Continental", "Breakfast"],
    area: "Indiranagar",
    address: "1st Floor, 100 Feet Road, Indiranagar, Bangalore",
    rating: 4.3,
    costForTwo: 1400,
    groupFriendly: true,
    maxGroupSize: 8,
    ambiance: ["Cozy", "Artsy", "Brunch-Vibe"],
    highlights: ["All-Day Breakfast", "European Menu", "Great Coffee"],
    lat: 12.9786,
    lng: 77.6399,
  },
  {
    id: "resto-010",
    name: "CTR (Central Tiffin Room)",
    cuisine: ["South Indian", "Dosa", "Traditional"],
    area: "Malleshwaram",
    address: "7th Cross, Margosa Road, Malleshwaram, Bangalore",
    rating: 4.4,
    costForTwo: 200,
    groupFriendly: true,
    maxGroupSize: 6,
    ambiance: ["Heritage", "Bustling", "Street-Style"],
    highlights: ["Benne Masala Dosa", "Iconic Since 1920s", "Morning Queue"],
    lat: 13.0035,
    lng: 77.5687,
  },
  {
    id: "resto-011",
    name: "The Black Pearl",
    cuisine: ["Seafood", "Coastal", "Mangalorean"],
    area: "HSR Layout",
    address: "14th Main, HSR Layout Sector 4, Bangalore",
    rating: 4.2,
    costForTwo: 1000,
    groupFriendly: true,
    maxGroupSize: 8,
    ambiance: ["Nautical-Theme", "Casual", "Warm"],
    highlights: ["Fresh Seafood", "Coastal Flavors", "Neer Dosa"],
    lat: 12.9116,
    lng: 77.6389,
  },
  {
    id: "resto-012",
    name: "Windmills Craftworks",
    cuisine: ["European", "Craft Beer", "Pizza"],
    area: "Whitefield",
    address: "Whitefield Main Road, Near ITPL, Bangalore",
    rating: 4.3,
    costForTwo: 2200,
    groupFriendly: true,
    maxGroupSize: 15,
    ambiance: ["Industrial-Chic", "Brewery", "Spacious"],
    highlights: ["Award-Winning Brews", "Wood-Fired Pizza", "Live Music"],
    lat: 12.9698,
    lng: 77.7499,
  },
  {
    id: "resto-013",
    name: "Nagarjuna",
    cuisine: ["Andhra", "Biryani", "South Indian"],
    area: "Residency Road",
    address: "44/1, Residency Road, Bangalore",
    rating: 4.3,
    costForTwo: 700,
    groupFriendly: true,
    maxGroupSize: 10,
    ambiance: ["Traditional", "Bustling", "Family"],
    highlights: ["Andhra Meals on Banana Leaf", "Spicy Biryani", "Iconic"],
    lat: 12.9722,
    lng: 77.6085,
  },
  {
    id: "resto-014",
    name: "Burma Burma",
    cuisine: ["Burmese", "Asian", "Vegetarian"],
    area: "Indiranagar",
    address: "100 Feet Road, Indiranagar, Bangalore",
    rating: 4.4,
    costForTwo: 1500,
    groupFriendly: true,
    maxGroupSize: 8,
    ambiance: ["Elegant", "Minimalist", "Zen"],
    highlights: ["Pure Vegetarian", "Burmese Cuisine", "Tea Leaf Salad"],
    lat: 12.9781,
    lng: 77.6403,
  },
  {
    id: "resto-015",
    name: "Glen's Bakehouse",
    cuisine: ["Bakery", "Continental", "Cafe"],
    area: "Indiranagar",
    address: "6th Main, HAL 2nd Stage, Indiranagar, Bangalore",
    rating: 4.5,
    costForTwo: 800,
    groupFriendly: true,
    maxGroupSize: 6,
    ambiance: ["Cozy", "Warm", "Bakery-Fresh"],
    highlights: ["Artisan Bread", "Pastries", "Best Cakes in Bangalore"],
    lat: 12.9774,
    lng: 77.6401,
  },
  {
    id: "resto-016",
    name: "Copitas",
    cuisine: ["Latin American", "Mexican", "Cocktails"],
    area: "Koramangala",
    address: "80 Feet Road, Koramangala 4th Block, Bangalore",
    rating: 4.1,
    costForTwo: 1800,
    groupFriendly: true,
    maxGroupSize: 10,
    ambiance: ["Vibrant", "Latin", "Party"],
    highlights: ["Tequila Bar", "Tacos", "Late Night"],
    lat: 12.9355,
    lng: 77.6241,
  },
  {
    id: "resto-017",
    name: "Karavalli",
    cuisine: ["Coastal Karnataka", "Kerala", "Seafood"],
    area: "Residency Road",
    address: "The Gateway Hotel, 66 Residency Road, Bangalore",
    rating: 4.6,
    costForTwo: 3000,
    groupFriendly: true,
    maxGroupSize: 8,
    ambiance: ["Premium", "Traditional", "Fine-Dining"],
    highlights: ["Award-Winning", "Coastal Cuisine", "Heritage Recipes"],
    lat: 12.9718,
    lng: 77.6091,
  },
  {
    id: "resto-018",
    name: "Barbecue Nation",
    cuisine: ["BBQ", "North Indian", "Multi-Cuisine"],
    area: "JP Nagar",
    address: "15th Cross, JP Nagar Phase 1, Bangalore",
    rating: 4.0,
    costForTwo: 1200,
    groupFriendly: true,
    maxGroupSize: 20,
    ambiance: ["Family", "Buffet-Style", "Lively"],
    highlights: ["Live Grill", "Unlimited Buffet", "Group-Friendly"],
    lat: 12.9107,
    lng: 77.5852,
  },
  {
    id: "resto-019",
    name: "Koshys",
    cuisine: ["Continental", "Indian", "Cafe"],
    area: "St. Marks Road",
    address: "39, St. Marks Road, Bangalore",
    rating: 4.2,
    costForTwo: 800,
    groupFriendly: true,
    maxGroupSize: 8,
    ambiance: ["Heritage", "Old-Bangalore", "Nostalgic"],
    highlights: ["Since 1940", "Literary History", "Old-World Charm"],
    lat: 12.9726,
    lng: 77.6021,
  },
  {
    id: "resto-020",
    name: "AB's - Absolute Barbecues",
    cuisine: ["BBQ", "Multi-Cuisine", "Grills"],
    area: "HSR Layout",
    address: "27th Main, HSR Layout Sector 1, Bangalore",
    rating: 4.2,
    costForTwo: 1300,
    groupFriendly: true,
    maxGroupSize: 15,
    ambiance: ["Modern", "Fun", "Interactive"],
    highlights: ["DIY Grills", "Unlimited Menu", "Party Packages"],
    lat: 12.9121,
    lng: 77.6376,
  },
];
